In [3]:
import tensorflow as tf
import numpy as np

In [4]:
keys = [[0, 0]]
count = [0]

@tf.function
def rng_next():
    count[0] += 1
    if count[0] % 2 == 0:
        return keys[0]
    else:
        new_key, keys[0] = tf.random.split(keys[0])
        return keys[0]

In [5]:
a = np.arange(72).reshape(24, 3)

ds = tf.data.Dataset.from_tensor_slices(a)
ds = ds.batch(4)
ds.map(lambda x: {"ind":x})

<_MapDataset element_spec={'ind': TensorSpec(shape=(None, 3), dtype=tf.int64, name=None)}>

In [6]:
ds = ds.map(lambda x: {"ind":x})

In [7]:
ds.element_spec

{'ind': TensorSpec(shape=(None, 3), dtype=tf.int64, name=None)}

In [15]:
def curry1(f):
    """Supply all arguments but the first."""

    def fc(*args, **kwargs):
        return lambda x: f(x, *args, **kwargs)

    return fc

@curry1
def f(x):
    x.update({"i":0})
    return x

In [16]:
ds = ds.map(f)

TypeError: Unsupported return value from function passed to Dataset.map(): <function outer_factory.<locals>.inner_factory.<locals>.tf__fc.<locals>.<lambda> at 0x7f7edc6ceb00>.

In [5]:
# g = tf.random.Generator.from_seed(0)

# def sampler(x):
#     key = rng_next()
#     return {"a": x, "grid": tf.random.stateless_uniform([5], key, 100),}

# ds = ds.map(sampler)

In [38]:
for d in ds.take(2):
    print(d)

{'a': <tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])>, 'grid': <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [2, 3]], dtype=int32)>}
{'a': <tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]]])>, 'grid': <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [2, 3]], dtype=int32)>}
