In [7]:
import torch

def prepare_slice_index(
    input_dict ,
    slice_keys,
):
    """
    Used in fourier-like architectures.

    For example:
        input_dict = {"x": 1, "y": 2, "z": 1}
        slice_keys = ["x", "z"]
        return tensor([0, 3])
    """
    index_dict = {}
    c = 0
    for key, size in input_dict.items():
        index_dict[key] = []
        for _ in range(size):
            index_dict[key].append(c)
            c += 1
    slice_index = []
    print(index_dict)
    for key in slice_keys:
        slice_index += index_dict[key]
    return torch.tensor(slice_index)

In [8]:
input_dict = {"x": 1, "y": 2, "z": 1}
slice_keys = ["x", "z"]

In [9]:
prepare_slice_index(input_dict, slice_keys)

{'x': [0], 'y': [1, 2], 'z': [3]}


tensor([0, 3])

In [1]:
import torch

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
class DeepoNet(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.linear = torch.nn.Linear(4, 1)
        self.relu = torch.nn.ReLU()
        self.sigmoid = torch.nn.Sigmoid()
        self.tanh = torch.nn.Tanh()
        self.linear2 = torch.nn.Linear(1, 1)

    def forward(self,x):
        x = self.linear(x)
        x = self.relu(x)
        x = self.sigmoid(x)
        x = self.tanh(x)
        x = self.linear2(x)
        return x


In [3]:
net = DeepoNet()

In [18]:
for name, p in net.named_parameters():
    print(name, p)

linear.weight Parameter containing:
tensor([[-0.2110,  0.0316, -0.0930,  0.3671]], requires_grad=True)
linear.bias Parameter containing:
tensor([-0.4602], requires_grad=True)
linear2.weight Parameter containing:
tensor([[-0.8988]], requires_grad=True)
linear2.bias Parameter containing:
tensor([-0.8590], requires_grad=True)


In [27]:
p_init = dict(net.named_parameters())

def loss_fn(net, pre)
loss = sum([torch.sum(p - p_init[key]) for key, p in net.named_parameters()])

In [2]:
from modulus.sym.hydra import to_absolute_path, instantiate_arch, ModulusConfig, to_yaml
import os
import sys
import warnings

import numpy as np

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
file_path = "/workspace/modulus-sym/data/examples_sym/examples/anti_derivative/data/anti_derivative.npy"
if not os.path.exists(to_absolute_path(file_path)):
    warnings.warn(
        f"Directory {file_path} does not exist. Cannot continue. Please download the additional files from NGC https://catalog.ngc.nvidia.com/orgs/nvidia/teams/modulus/resources/modulus_sym_examples_supplemental_materials"
    )
    sys.exit()

data = np.load(to_absolute_path(file_path), allow_pickle=True).item()
x_train = data["x_train"]
a_train = data["a_train"]
u_train = data["u_train"]

# load test data
x_test = data["x_test"]
a_test = data["a_test"]
u_test = data["u_test"]

In [5]:
a_train.shape

(10000, 100)